spring:
  redis:
    #数据库索引
    database: 0
    host: 192.168.232.128
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  datasource:
    username: root
    password: 9527
    url: jdbc:mysql://localhost:3306/spring_cache
    driver-class-name: com.mysql.jdbc.Driver

#驼峰开启 lastName=last_name
mybatis:
  configuration:
    map-underscore-to-camel-case: true